shuffle: roundrobin
# Deployment mode: 'local' for local deployment, 'ansible' for remote deployment via Ansible
deployment_mode: ansible
config:
  activeEpoch: 18
  keyType: "hash-sig"
validators:
  - name: "ethlambda_1"
    privkey: "bdf953adc161873ba026330c56450453f582e3c4ee6cb713644794bcfdd85fe5"
    enrFields:
      ip: "46.224.123.223"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "ream_0"
    privkey: "af27950128b49cda7e7bc9fcb7b0270f7a3945aa7543326f3bfdbd57d2a97a32"
    enrFields:
      ip: "77.42.27.219"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    devnet: 1
    count: 1
  - name: "qlean_0"
    privkey: "c2bbdac5e876b3e9d4b8b6b8c2bbdac5e876b3e9d4b8b6b8c2bbdac5e876b3e9"
    enrFields:
      ip: "46.224.123.220"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "lantern_0"
    privkey: "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5"
    enrFields:
      ip: "46.224.135.177"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "qlean_1"
    privkey: "64a7f5ab53907966374ca23af36392910af682eec82c12e3abbb6c2ccdf39a72"
    # verify /ip4/37.27.250.20/udp/9001/quic-v1/p2p/16Uiu2HAmErASHzouSQumaetyU18brt4HNUm4151K55ySBQMRLzSS
    enrFields:
      ip: "37.27.250.20"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "ethlambda_0"
    # node id 86cec93353ffcc6f38c9c15becadcb30d1acab21a92b30418110c980a38d9c3d
    # peer id 16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    privkey: "299550529a79bc2dce003747c52fb0639465c893e00b0440ac66144d625e066a"
    # verify /ip4/78.47.44.215/udp/9001/quic-v1/p2p/16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    enrFields:
      ip: "78.47.44.215"
      quic: 9001
    metricsPort: 9095
    isAggregator: true
    count: 1
